import type { Metadata } from 'next'
import Link from 'next/link'
import './global.css'
import { poppins, robotoMono } from '@/app/fonts';
import Nav from '@/app/components/nav'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={poppins.className}>
            <body className='m-0 p-0 absolute top-0'>
                <nav className='max-h-screen fixed w-[300px] py-6 pl-6 overflow-hidden'>
                    <h1 className='text-3xl mb-2'>Sam Waite</h1>
                    <div className='mb-5'>Software Developer, Web Developer, Open-source enthusiast</div>
                    <Nav />
                </nav>
                <div className='ml-[300px] fixed w-px h-screen bg-black'></div>
                <main className='pl-[301px] w-screen'>
                    {children}
                </main>
            </body>
        </html>
    )
}
